### PR TITLE
Update FullCalendar to v4.2.0

### PR DESCRIPTION
**Pull request by lan0**
This updates FullCalendar and Scheduler to v4.2.0.

The list of options and events is updated and should be current.

`ember-auto-import` is included to import FullCalendar ES6 packages.

A config option is added to import CSS files of the FullCalendar plugins.

To update options on the calendar object, `Calendar::mutateOptions()` is used like in the [React component](https://github.com/fullcalendar/fullcalendar-react/blob/master/src/FullCalendar.tsx) (Thanks @jir-f).

The test `it supports changes in resources array` is currently getting skipped, I think that the resource plugin doesn't work correctly in the test...

### CODE REVIEW

**Comment by MichalBryxi** [comment]
Trying to port my older code to this branch and I bumped into a problem that according to the [upgrade guide](https://fullcalendar.io/docs/upgrading-from-v3) the `agendaWeek` and `agendaDay` moved to `timeGrid` [plugin](https://fullcalendar.io/docs/timegrid-view). While this plugin imports `@fullcalendar/daygrid`, it does not import `@fullcalendar/timegrid`.

I don't know whether it is the intention of this addon to provide all the plugins(?) I fixed the problem in my code by adding:

```js
// package.json
...
  "devDependencies": {
    "@fullcalendar/timegrid": "~4.3.0",
  }
...
```

```js
// controller.js
import timeGridPlugin from "@fullcalendar/timegrid";

export default Controller.extend({
  init() {
    this._super(...arguments);
    this.plugins = [timeGridPlugin];
  }
});
```

```hbs
{{full-calendar plugins=plugins}}
```

In case anyone else bumps into this.

**Comment by lan0** [comment]
@MichalBryxi you're right, you have to add the plugins you want to use as dependencies yourself.

Did timegrid work for you without importing any css? I implemented a [`plugins` option](https://github.com/scoutforpets/ember-fullcalendar/blob/428a31a5eddae1df4ec681f239da9b2c692fa56d/README.md#plugins) for this.

**Comment by MichalBryxi** [comment]
In the meantime I bumped my app to `ember@3.15` and went with native classes & angle bracket components. I am not sure if that is related at all, but I also had to add a `@fullcalendar/moment` plugin as described in  the [docs](https://fullcalendar.io/docs/date-formatting#formatting-strings).

@lan0 I can see that you have the work with the plugins in the readme and maybe it's just me migrating from <v4 and expecting things to just work.

The calendar looks funny without the imported CSS:

Screenshot 2020-01-22 at 08 17 14

When I tried to blindly copy-paste the example config and including my option:
```js
    emberFullCalendar: {
      plugins: ["core", "daygrid", "list", "timegrid"]
    }
```

I get:
```
❯ ember server
Cannot find module '@fullcalendar/list/package.json' from '/Users/mbryxi/Projects/kasa/ui/node_modules/ember-fullcalendar'
```

Descriptive error message would be nice.

When I fixed all those errors:

Screenshot 2020-01-22 at 08 22 47

Looks good to me. Great work!

**Comment by kushthedude** [comment]
@lan0 Any updates here ?

**Comment by adet4ever** [comment]
Perhaps the changes can be applied to the main branch?

**Review by lasantha57 — APPROVED** [review]

**Comment by MichalBryxi** [comment]
🦗  @lan0 ?

**Comment by lan0** [comment]
The view names are passed in from the app code, no changes needed in the addon.

**Comment by MichalBryxi** [comment]
Sorry. I should have been more specific: Anything blocks merging this? Since @lasantha57 approved, CI is green can someone just hit the "merge" button? @lan0 ?

**Comment by lan0** [comment]
I don't have write access to this repo so I can't merge, sorry :(

**Comment by aatauil** [comment]
No advancements on the the PR actually being merged?  Would love to use the upgraded version...

**Comment by jamesdixon** [comment]
Hi everyone, sorry for not merging this sooner. Would anyone be willing to update it to 4.4.1 so we're on the latest 4.x version of FC?

**Comment by jamesdixon** [comment]
@lan0 I've given you write access to the repo. Can you please tag it as a 2.x release? Let me know your NPM info and I can give you publishing access there as well.

**Comment by lan0** [comment]
Thank you @jamesdixon.

I've bumped the FC version, merged the PR, tagged a new 2.0.0 release and created an account on npm with the same username.

**Comment by jamesdixon** [comment]
@lan0 thanks! Invite to NPM sent.

Appreciate your help with this

**Pull request merged**
