### PR TITLE
Minimal fastboot support

### PR DESCRIPTION
**Pull request by plcarmel**

### CODE REVIEW

**Comment by jamesdixon** [comment]
@plcarmel thanks for submitting. I don't use Fastboot, so I really have no way to verify this.

That said, in your description, you mention not including bower files. None of the FullCalendar assets are via bower at this point; it's all handled via NPM. Is this still applicable?

Thanks!

**Comment by plcarmel** [comment]
Hi @jamesdixon.  Yes it is still applicable; I updated the name of the commit to fix my mistake.  I was confused by the fast that you still provide a blueprint that installs the bower packages. I deleted the blueprint.

Fastboot doesn't include jQuery so any Fastboot application using the addon will crash otherwise.

I slightly modified the dummy app to make it compatible fastboot so you can test my modification.  Just type `ember fastboot --serve-assets` instead of `ember serve` and there you go !

**Comment by jamesdixon** [comment]
@plcarmel awesome! thank you for the explanation. I'll give it a shot 👍

**Comment by jamesdixon** [comment]
released in 1.7.0

thanks!

**Comment by plcarmel** [comment]
You're welcome :)

**Pull request merged**
