### PR TITLE
Support eventSources parameter

### PR DESCRIPTION
**Pull request by Moxide**
Reference :  #24
I removed the rerenders, which seems to be unnecessary when using **addEventSource**.
I thought we could use this one-liner :
`fc.fullCalendar( 'refetchEventSources', this.get('eventSources'));`
but it's not working in my setup...

Note: The merge I did includes the work from @beverlyguillermo , which should fix the IE compatibility issue, mentioned here : #23

### CODE REVIEW

**Comment by jamesdixon** [comment]
Does adding back the `rerender` call fix your issue?

**Comment by jamesdixon** [comment]
Also, just an FYI that I'm moving away from using this addon.

There's a pure Ember calendar implementation called [ember-calendar](https://github.com/alphasights/ember-calendar). I looked into using it a long time ago, but it didn't support month and day views, which I needed. However, someone just recently implemented those views, so I've been working on helping him with it and in all honesty, it's really great. There's still work to be done, but I think it's going to be better in the long run.

If you want to give it a shot, check out my branch: https://github.com/scoutforpets/ember-calendar/tree/master

**Comment by Moxide** [comment]
Just tried the rerenders, and no hope :-(
Thanks for pointing out **ember-calendar**, indeed it seems most promising and very "ember friendly" !

**Comment by jamesdixon** [comment]
@Moxide yeah, not sure what to tell ya at this point. If you get it working, let me know.

Yeah, I believe `ember-calendar` is going to be the future. FullCalendar is great, but I think it's becoming a bit bloated. Plus, there was a huge decrease in 2.x (still in 3.x) performance when rendering lots of events, which is why I needed another solution.

Let me know if you'd like to help with `ember-calendar`.

Cheers.

**Comment by Moxide** [comment]
Actually, it **is** working ;-) It's just that it would have been more elegant to use a one-liner :-)

I totally agree with the slowness of fullcalendar when showing big numbers of events, but when you need complex behavior, there is no alternative today IMO. 
For instance, in a big project, I made intensive use of scheduler, background rendering, all day events, event constraints... etc. Would have been a lot of pain to develop those from scratch !
Would be glad to help though ;-)
Regards.

**Comment by jamesdixon** [comment]
@Moxide agreed. It's definitely the most full-featured option out there. However, I'm finding that with ember-calendar being component-based, it seems much easier to develop with. However, there are definitely still missing features.

**Comment by jamesdixon** [comment]
Regarding the work of @beverlyguillermo, wasn't that already merged?

**Comment by Moxide** [comment]
Well I don't think so, at least it's not shown the fork graph...

**Comment by jamesdixon** [comment]
@Moxide let me know when this is ready to be reviewed.

Regarding the `Object.assign` polyfill, I wonder if it makes sense to just replace it with the solution suggest by @rliebeskind in #23. It wouldn't add any additional code. Thoughts?

**Comment by Moxide** [comment]
Hello,
About the **Object.assign**, I haven't tested the solution from #23, but it seems to be ok.
About the other part, I using this in a production environment without any problem. 
Besides that, I just committed  some modifications to take into account the new Fullcalendar 3 parameters.

**Pull request merged**
