### PR TITLE
observe events array

### PR DESCRIPTION
**Pull request by miguelcobain**
this makes fullcalendar reflect changes in the events array

Also has some nice tests to prove that :)

### CODE REVIEW

**Comment by miguelcobain** [comment]
Some actions could be further improved.
For example, actions like `eventDrop` and `eventResize` could pass in `originalObject` instead of the "wrapper" we now create.

**Comment by jamesdixon** [comment]
Sorry for the delay. Was in the midst of a cross-country trip back home!

I'll get these merged in tomorrow. Thanks for all of the great tips/contributions!

**Comment by DanChadwick** [comment]
Any progress on this? I'd like to see this too!

**Comment by jamesdixon** [comment]
@DanChadwick sorry for the delay. I was sidetracked with other work, but will do my best to get these merged in soon. I believe there were a couple of breaking changes, so I need to update the docs as well.

**Comment by DanChadwick** [comment]
@jamesdixon - Never a need to apologize! I'm grateful for every OSS contributor's generosity with their time and expertise.

**Comment by miguelcobain** [comment]
@jamesdixon if have any question regarding the changes, I'd be happy to answer.

**Comment by rwwagner90** [comment]
@miguelcobain I tried merging this in, and I wasn't really sure why it wasn't working.

Why have so many observers and such? Shouldn't something like this be all we need?

```
updateEvents: observer('events.[]', function() {
    var fullCalendarElement = this.$();
    fullCalendarElement.fullCalendar('removeEvents');
    fullCalendarElement.fullCalendar('addEventSource', this.get('events'));
    fullCalendarElement.fullCalendar('rerenderEvents' );
  }),
```

**Comment by jamesdixon** [comment]
@miguelcobain I also had a question. In my current code, I'm using the FC `events` method that returns a function (http://fullcalendar.io/docs/event_data/events_function/). I'm using it so I can get the start/end date of the range and then request only events for those days. Unfortunately, this no longer works with the updated approach. I'm guessing you are probably doing something similar; if so, how are you approaching it?

**Comment by rwwagner90** [comment]
@miguelcobain just wanted to offer my two cents here. What if we use http://fullcalendar.io/docs/utilities/handlers/ and set up some on next/previous handlers, that would update the start/end date of the range we are currently viewing, thus allowing us to track the range in the Ember addon and update the events we want to display with an observer on when the range changes?

**Comment by miguelcobain** [comment]
@rwwagner90 if you use `observer('events.[]', function() {` it will trigger on all changes of the array.
You don't have access to which elements were added or removed.
Your suggestion works, but it is always removing events and re-adding them, possibily re-rendering the same unchanged events needlessly.

With my approach, I'm basically adding to FC what was added in the array and removing from FC what was removed from the array.

**Comment by miguelcobain** [comment]
@jamesdixon you can use [`viewRender` callback](http://fullcalendar.io/docs/display/viewRender/). It gets passed in a [view object](http://fullcalendar.io/docs/views/View_Object/) with which you can obtain any information about the current rendered view (e.g `view.start` and `view.end`).

**Pull request merged**
