### PR TITLE
date changes

### PR DESCRIPTION
**Pull request by miguelcobain**
Same reasoning for date.
This (along with viewName) allows us to control the calendar using a data down approach.

### CODE REVIEW

**Comment by jamesdixon** [comment]
I just tried to set `defaultDate` on the component and it doesn't work, which is I believe what your reference was to `viewName` not being automatically inserted. From the FC documentation, this appears to be the correct option to set the start date when the calendar loads. The solution you provided works, but I'm not convinced it's necessary. Thoughts?

**Comment by DanChadwick** [comment]
I too would like to be able to navigate the current date from outside the component.

**Comment by DanChadwick** [comment]
This PR seems solid and would allow me to delete the observer that I'm using. It is in accordance with Ember's Data-Down/Actions-Up methodology.

@jamesdixon: `defaultDate` only sets the date when `fullcalendar` is initially displayed. This PR adds a new `date` attribute that can be bound in the template. When `date` changes, `ember-fullcalendar` will cause `fullcalendar` to navigate to the new date.

**Comment by rwwagner90** [comment]
@DanChadwick I agree that this looks to be a pretty straight forward and small PR. I will look into merging it when I get home tonight.

**Comment by jamesdixon** [comment]
closed via  3bd8852

**Pull request closed without merging**
